
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import metodos_estaticos.Servicio;
import modelo.Problema;
import servicios.ConexionConcurso;
import servicios.RegistroProblema;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlo
 */
public class GUI_NuevoProblema extends javax.swing.JFrame {
    private int contador;
    private File fichero, file2;
    private File inp,out;
    Problema p1;
    private int id_problemsetter;

    /**
     * Creates new form GUI_NuevoProblema
     */
    public GUI_NuevoProblema(int id) {
        contador = 0;
        p1 = new Problema();
        initComponents();
        id_problemsetter = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_fuente_archivo = new javax.swing.JButton();
        btn_subir = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        btn_output = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        btn_fuente_archivo.setText("Seleccionar Fuente");
        btn_fuente_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fuente_archivoActionPerformed(evt);
            }
        });

        btn_subir.setText("Subir");
        btn_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btn_input.setText("Seleccionar input");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        btn_output.setText("Seleccionar output");
        btn_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_regresar))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_subir)
                    .addComponent(btn_fuente_archivo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_output, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(btn_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_regresar)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_fuente_archivo)
                .addGap(18, 18, 18)
                .addComponent(btn_input)
                .addGap(18, 18, 18)
                .addComponent(btn_output)
                .addGap(43, 43, 43)
                .addComponent(btn_subir)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_fuente_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fuente_archivoActionPerformed
     try {
            // TODO add your handling code here:
            metodo("fuente.pdf");
        } catch (IOException ex) {
            Logger.getLogger(GUI_SubirProblema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_fuente_archivoActionPerformed

    private void btn_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirActionPerformed
        try {
            switch(contador)
            {
                case 0:
                    Servicio.copyFileUsingStream(fichero, file2);
                    p1.setRutaArchivo(file2.getAbsolutePath());
                   
                    break;
                case 1:
                     Servicio.copyFileUsingStream(fichero, inp);
                      p1.setRuta_input(inp.getAbsolutePath());
                      
                    break;
                case 2:
                    Servicio.copyFileUsingStream(fichero, out);
                     
                    p1.setRuta_output(out.getAbsolutePath());
                    p1.setId_problem_setter(id_problemsetter);
                    p1.setNombre(txt_nombre.getText());
                    
                    RegistroProblema rg1 = new RegistroProblema();
                    rg1.registrar(p1);
                    break;
            }
          
            
            contador = (contador + 1)%3;
        } catch (IOException ex) {
            Logger.getLogger(GUI_NuevoProblema.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_NuevoProblema.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_NuevoProblema.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_subirActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        this.setVisible(false);
        new GUI_Menu().setVisible(true);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
      try {
            // TODO add your handling code here:
            metodo("input.txt");
        } catch (IOException ex) {
            Logger.getLogger(GUI_SubirProblema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outputActionPerformed
       try {
            // TODO add your handling code here:
            metodo("output.txt");
        } catch (IOException ex) {
            Logger.getLogger(GUI_SubirProblema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_outputActionPerformed

    
    public void metodo(String tipo) throws IOException
    {
            //Creamos selector de apertura
      JFileChooser fc=new JFileChooser();
 
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showOpenDialog(null);

        //Si el usuario, pincha en aceptar
        if(seleccion==JFileChooser.APPROVE_OPTION) {
            //Seleccionamos el fichero
            fichero=fc.getSelectedFile();
            
            System.out.println(fichero.getAbsolutePath());
            switch(tipo.toString())
            {
                case "fuente.pdf":
                    file2 = new File("C:\\Users\\Carlo\\Downloads\\ProblemasPDF_Programacion\\"+txt_nombre.getText()+tipo);
                    break;
                case "input.txt":
                    inp = new File("C:\\Users\\Carlo\\Downloads\\ProblemasPDF_Programacion\\"+txt_nombre.getText()+tipo);
                    break;
                case "output.txt":
                    out = new File("C:\\Users\\Carlo\\Downloads\\ProblemasPDF_Programacion\\"+txt_nombre.getText()+tipo);
                    break;
            }
            
            
            //compileFile(fichero.getAbsolutePath());
            
            btn_fuente_archivo.setText(fichero.getAbsolutePath());
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fuente_archivo;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_output;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_subir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
